def init_drpai(fd) -> int: ...

def buffer_alloc_dmabuf(buf_size) -> dma_buffer: ...

def memcpy(buf1, buf2, size) -> None: ...

def buffer_flush_dmabuf(idx, size) -> int: ...

def get_result(runtime) -> list[detection]: ...
